// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/review-service/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/review-service/pkg/db/ent/reviewrule"
	"github.com/google/uuid"
)

// ReviewRuleQuery is the builder for querying ReviewRule entities.
type ReviewRuleQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ReviewRule
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReviewRuleQuery builder.
func (rrq *ReviewRuleQuery) Where(ps ...predicate.ReviewRule) *ReviewRuleQuery {
	rrq.predicates = append(rrq.predicates, ps...)
	return rrq
}

// Limit adds a limit step to the query.
func (rrq *ReviewRuleQuery) Limit(limit int) *ReviewRuleQuery {
	rrq.limit = &limit
	return rrq
}

// Offset adds an offset step to the query.
func (rrq *ReviewRuleQuery) Offset(offset int) *ReviewRuleQuery {
	rrq.offset = &offset
	return rrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rrq *ReviewRuleQuery) Unique(unique bool) *ReviewRuleQuery {
	rrq.unique = &unique
	return rrq
}

// Order adds an order step to the query.
func (rrq *ReviewRuleQuery) Order(o ...OrderFunc) *ReviewRuleQuery {
	rrq.order = append(rrq.order, o...)
	return rrq
}

// First returns the first ReviewRule entity from the query.
// Returns a *NotFoundError when no ReviewRule was found.
func (rrq *ReviewRuleQuery) First(ctx context.Context) (*ReviewRule, error) {
	nodes, err := rrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{reviewrule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rrq *ReviewRuleQuery) FirstX(ctx context.Context) *ReviewRule {
	node, err := rrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReviewRule ID from the query.
// Returns a *NotFoundError when no ReviewRule ID was found.
func (rrq *ReviewRuleQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{reviewrule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rrq *ReviewRuleQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReviewRule entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReviewRule entity is found.
// Returns a *NotFoundError when no ReviewRule entities are found.
func (rrq *ReviewRuleQuery) Only(ctx context.Context) (*ReviewRule, error) {
	nodes, err := rrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{reviewrule.Label}
	default:
		return nil, &NotSingularError{reviewrule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rrq *ReviewRuleQuery) OnlyX(ctx context.Context) *ReviewRule {
	node, err := rrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReviewRule ID in the query.
// Returns a *NotSingularError when more than one ReviewRule ID is found.
// Returns a *NotFoundError when no entities are found.
func (rrq *ReviewRuleQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{reviewrule.Label}
	default:
		err = &NotSingularError{reviewrule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rrq *ReviewRuleQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReviewRules.
func (rrq *ReviewRuleQuery) All(ctx context.Context) ([]*ReviewRule, error) {
	if err := rrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rrq *ReviewRuleQuery) AllX(ctx context.Context) []*ReviewRule {
	nodes, err := rrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReviewRule IDs.
func (rrq *ReviewRuleQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := rrq.Select(reviewrule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rrq *ReviewRuleQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rrq *ReviewRuleQuery) Count(ctx context.Context) (int, error) {
	if err := rrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rrq *ReviewRuleQuery) CountX(ctx context.Context) int {
	count, err := rrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rrq *ReviewRuleQuery) Exist(ctx context.Context) (bool, error) {
	if err := rrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rrq *ReviewRuleQuery) ExistX(ctx context.Context) bool {
	exist, err := rrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReviewRuleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rrq *ReviewRuleQuery) Clone() *ReviewRuleQuery {
	if rrq == nil {
		return nil
	}
	return &ReviewRuleQuery{
		config:     rrq.config,
		limit:      rrq.limit,
		offset:     rrq.offset,
		order:      append([]OrderFunc{}, rrq.order...),
		predicates: append([]predicate.ReviewRule{}, rrq.predicates...),
		// clone intermediate query.
		sql:    rrq.sql.Clone(),
		path:   rrq.path,
		unique: rrq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ObjectType string `json:"object_type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReviewRule.Query().
//		GroupBy(reviewrule.FieldObjectType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rrq *ReviewRuleQuery) GroupBy(field string, fields ...string) *ReviewRuleGroupBy {
	grbuild := &ReviewRuleGroupBy{config: rrq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rrq.sqlQuery(ctx), nil
	}
	grbuild.label = reviewrule.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ObjectType string `json:"object_type,omitempty"`
//	}
//
//	client.ReviewRule.Query().
//		Select(reviewrule.FieldObjectType).
//		Scan(ctx, &v)
//
func (rrq *ReviewRuleQuery) Select(fields ...string) *ReviewRuleSelect {
	rrq.fields = append(rrq.fields, fields...)
	selbuild := &ReviewRuleSelect{ReviewRuleQuery: rrq}
	selbuild.label = reviewrule.Label
	selbuild.flds, selbuild.scan = &rrq.fields, selbuild.Scan
	return selbuild
}

func (rrq *ReviewRuleQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rrq.fields {
		if !reviewrule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rrq.path != nil {
		prev, err := rrq.path(ctx)
		if err != nil {
			return err
		}
		rrq.sql = prev
	}
	return nil
}

func (rrq *ReviewRuleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReviewRule, error) {
	var (
		nodes = []*ReviewRule{}
		_spec = rrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*ReviewRule).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &ReviewRule{config: rrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(rrq.modifiers) > 0 {
		_spec.Modifiers = rrq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rrq *ReviewRuleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rrq.querySpec()
	if len(rrq.modifiers) > 0 {
		_spec.Modifiers = rrq.modifiers
	}
	_spec.Node.Columns = rrq.fields
	if len(rrq.fields) > 0 {
		_spec.Unique = rrq.unique != nil && *rrq.unique
	}
	return sqlgraph.CountNodes(ctx, rrq.driver, _spec)
}

func (rrq *ReviewRuleQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (rrq *ReviewRuleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   reviewrule.Table,
			Columns: reviewrule.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: reviewrule.FieldID,
			},
		},
		From:   rrq.sql,
		Unique: true,
	}
	if unique := rrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reviewrule.FieldID)
		for i := range fields {
			if fields[i] != reviewrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rrq *ReviewRuleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rrq.driver.Dialect())
	t1 := builder.Table(reviewrule.Table)
	columns := rrq.fields
	if len(columns) == 0 {
		columns = reviewrule.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rrq.sql != nil {
		selector = rrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rrq.unique != nil && *rrq.unique {
		selector.Distinct()
	}
	for _, m := range rrq.modifiers {
		m(selector)
	}
	for _, p := range rrq.predicates {
		p(selector)
	}
	for _, p := range rrq.order {
		p(selector)
	}
	if offset := rrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (rrq *ReviewRuleQuery) ForUpdate(opts ...sql.LockOption) *ReviewRuleQuery {
	if rrq.driver.Dialect() == dialect.Postgres {
		rrq.Unique(false)
	}
	rrq.modifiers = append(rrq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return rrq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (rrq *ReviewRuleQuery) ForShare(opts ...sql.LockOption) *ReviewRuleQuery {
	if rrq.driver.Dialect() == dialect.Postgres {
		rrq.Unique(false)
	}
	rrq.modifiers = append(rrq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return rrq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rrq *ReviewRuleQuery) Modify(modifiers ...func(s *sql.Selector)) *ReviewRuleSelect {
	rrq.modifiers = append(rrq.modifiers, modifiers...)
	return rrq.Select()
}

// ReviewRuleGroupBy is the group-by builder for ReviewRule entities.
type ReviewRuleGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rrgb *ReviewRuleGroupBy) Aggregate(fns ...AggregateFunc) *ReviewRuleGroupBy {
	rrgb.fns = append(rrgb.fns, fns...)
	return rrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rrgb *ReviewRuleGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rrgb.path(ctx)
	if err != nil {
		return err
	}
	rrgb.sql = query
	return rrgb.sqlScan(ctx, v)
}

func (rrgb *ReviewRuleGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rrgb.fields {
		if !reviewrule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rrgb *ReviewRuleGroupBy) sqlQuery() *sql.Selector {
	selector := rrgb.sql.Select()
	aggregation := make([]string, 0, len(rrgb.fns))
	for _, fn := range rrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rrgb.fields)+len(rrgb.fns))
		for _, f := range rrgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rrgb.fields...)...)
}

// ReviewRuleSelect is the builder for selecting fields of ReviewRule entities.
type ReviewRuleSelect struct {
	*ReviewRuleQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rrs *ReviewRuleSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rrs.prepareQuery(ctx); err != nil {
		return err
	}
	rrs.sql = rrs.ReviewRuleQuery.sqlQuery(ctx)
	return rrs.sqlScan(ctx, v)
}

func (rrs *ReviewRuleSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rrs.sql.Query()
	if err := rrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rrs *ReviewRuleSelect) Modify(modifiers ...func(s *sql.Selector)) *ReviewRuleSelect {
	rrs.modifiers = append(rrs.modifiers, modifiers...)
	return rrs
}
