// Code generated by ent, DO NOT EDIT.

package reviewrule

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the reviewrule type in the database.
	Label = "review_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldObjectType holds the string denoting the object_type field in the database.
	FieldObjectType = "object_type"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldRules holds the string denoting the rules field in the database.
	FieldRules = "rules"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// FieldDeleteAt holds the string denoting the delete_at field in the database.
	FieldDeleteAt = "delete_at"
	// Table holds the table name of the reviewrule in the database.
	Table = "review_rules"
)

// Columns holds all SQL columns for reviewrule fields.
var Columns = []string{
	FieldID,
	FieldObjectType,
	FieldDomain,
	FieldRules,
	FieldCreateAt,
	FieldUpdateAt,
	FieldDeleteAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRules holds the default value on creation for the "rules" field.
	DefaultRules string
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt func() uint32
	// DefaultUpdateAt holds the default value on creation for the "update_at" field.
	DefaultUpdateAt func() uint32
	// UpdateDefaultUpdateAt holds the default value on update for the "update_at" field.
	UpdateDefaultUpdateAt func() uint32
	// DefaultDeleteAt holds the default value on creation for the "delete_at" field.
	DefaultDeleteAt func() uint32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
