// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// ReviewRule is the predicate function for reviewrule builders.
type ReviewRule func(*sql.Selector)
